In [1]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

from scipy.optimize import linprog



C:\Users\KIIT\.ipython\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
data = {
    'w': [1.4, 0.7, 3.41, 3.98, 0.765, 1.13, 11.39, 11.78, 6.18],
    'd': [96, 20340, 1278, 852, 4970, 3976, 12, 12, 2520]
}
df = pd.DataFrame(data)

# Total width
W = 12.0


In [3]:
# Total width

W = 12.0



In [4]:
# Width and amount associated with each demand

w = df.w.values

d = df.d.values



In [5]:
 

df['w'] = pd.to_numeric(df['w'], errors='coerce')

w = df.w.values.astype(float)



In [6]:
df['d'] = pd.to_numeric(df['d'], errors='coerce')

d = df.d.values.astype(float)



In [7]:
A = np.eye(df.shape[0])*(W//w)

c = np.ones_like(w)



In [8]:
A_ub = np.atleast_2d(w)

In [9]:
b_ub = np.atleast_1d(W)

In [10]:
sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0,None), integrality = 0)

In [11]:
sol_dual = linprog(-d, A_ub=A.T, b_ub=c, bounds=(0,None))



In [12]:
duals = -sol.ineqlin.marginals



In [13]:
def solve_knapsack(W, w, duals):

    return linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), integrality=1)



In [14]:
price_sol = solve_knapsack(W, w, duals)



In [15]:
for _ in range(1000):

    duals = -sol.ineqlin.marginals

    price_sol = solve_knapsack(W, w, duals)

    y = price_sol.x

    if 1 + price_sol.fun < -1e-4:

        print(f"Iteration: {_}; Reduced cost: {(1 + price_sol.fun):.3f}")

        A = np.hstack((A, y.reshape((-1, 1))))

        c = np.append(c, 1)

        sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None))

    else:

        break

 

Iteration: 0; Reduced cost: -0.533
Iteration: 1; Reduced cost: -0.509
Iteration: 2; Reduced cost: -0.241
Iteration: 3; Reduced cost: -0.235
Iteration: 4; Reduced cost: -0.039
Iteration: 5; Reduced cost: -0.055
Iteration: 6; Reduced cost: -0.055
Iteration: 7; Reduced cost: -0.009
Iteration: 8; Reduced cost: -0.007
Iteration: 9; Reduced cost: -0.007
Iteration: 10; Reduced cost: -0.002
Iteration: 11; Reduced cost: -0.003


In [16]:
np.ceil(sol.x).astype(int), A.T



(array([   0,    0,    0,    0,    0,    0,   12,   12,    0,    0,   10,
           0, 1628,   57,   15,    0,  852,    0, 1249,    0,   31]),
 array([[ 8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 17.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 15.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.,  0.,  2.,  0.,  0.,  1.],
        [ 2.,  1.,  0.,  0.,  3.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  3.,  3.,  0.,  0.,  1.],
        [ 0.,  5.,  0.,  0.,  3.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
        [ 1.,  1.,  2.,  0.,  4.,  0.,  0.,  0.,  0.],
        [ 0.,  3.,  2.,  0.,  4

In [17]:
A.T

array([[ 8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 17.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 15.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  2.,  0.,  0.,  1.],
       [ 2.,  1.,  0.,  0.,  3.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  3.,  3.,  0.,  0.,  1.],
       [ 0.,  5.,  0.,  0.,  3.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
       [ 1.,  1.,  2.,  0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  2.,  0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 4.,  1.,  1.,  0.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  9.,  1.,  0., 