Codes on 1D Rebar Optimisation using Knapsack and Genetic Algorithm

Distribution of demands on the basis of Greedy approach


In [ ]:
data = {
    "w": [1.4, 0.7, 3.41, 3.98, 0.765, 1.13,6.18],
    "d": [96, 20340, 1278, 852, 4970, 3976,2520],
    "W": [6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0,10.5]
}

def distribute_demand(d, W):
    total_W = sum(W)
    distribution = [(W_i / total_W) * d for W_i in W]


    rounded_distribution = [int(round(dist)) for dist in distribution]
    adjustment = d - sum(rounded_distribution)
    #Greedy Approach

    if adjustment != 0:

        fractional_parts = [(distribution[i] % 1, i) for i in range(len(W))]
        fractional_parts.sort(reverse=True, key=lambda x: x[0])


        for _, idx in fractional_parts[:abs(adjustment)]:
            rounded_distribution[idx] += 1 if adjustment > 0 else -1

    return rounded_distribution

formatted_results = []

for i, w in enumerate(data['w']):
    d_value = data['d'][i]
    distribution = distribute_demand(d_value, data['W'])

    for j, W in enumerate(data['W']):
        if distribution[j] > 0:
            formatted_results.append(f"{w}\t{distribution[j]}\t{W}")


for result in formatted_results:
    print(result)


1.4	7	6.0
1.4	8	6.5
1.4	8	7.0
1.4	9	7.5
1.4	9	8.0
1.4	10	8.5
1.4	10	9.0
1.4	11	9.5
1.4	12	10.0
1.4	12	10.5
0.7	1479	6.0
0.7	1603	6.5
0.7	1726	7.0
0.7	1849	7.5
0.7	1972	8.0
0.7	2096	8.5
0.7	2219	9.0
0.7	2342	9.5
0.7	2465	10.0
0.7	2589	10.5
3.41	93	6.0
3.41	101	6.5
3.41	108	7.0
3.41	116	7.5
3.41	124	8.0
3.41	132	8.5
3.41	139	9.0
3.41	147	9.5
3.41	155	10.0
3.41	163	10.5
3.98	63	6.0
3.98	67	6.5
3.98	72	7.0
3.98	77	7.5
3.98	83	8.0
3.98	88	8.5
3.98	93	9.0
3.98	98	9.5
3.98	103	10.0
3.98	108	10.5
0.765	361	6.0
0.765	392	6.5
0.765	422	7.0
0.765	452	7.5
0.765	482	8.0
0.765	512	8.5
0.765	542	9.0
0.765	572	9.5
0.765	602	10.0
0.765	633	10.5
1.13	289	6.0
1.13	313	6.5
1.13	337	7.0
1.13	361	7.5
1.13	386	8.0
1.13	410	8.5
1.13	434	9.0
1.13	458	9.5
1.13	482	10.0
1.13	506	10.5
6.18	183	6.0
6.18	199	6.5
6.18	214	7.0
6.18	229	7.5
6.18	244	8.0
6.18	260	8.5
6.18	275	9.0
6.18	290	9.5
6.18	305	10.0
6.18	321	10.5


Computing the fulfillment on basis of Greedy Approach

In [1]:
import numpy as np

# Given data for w, d, and W
data = [
    (1.4, 7, 6.0),
    (1.4, 8, 6.5),
    (1.4, 8, 7.0),
    (1.4, 9, 7.5),
    (1.4, 9, 8.0),
    (1.4, 10, 8.5),
    (1.4, 10, 9.0),
    (1.4, 11, 9.5),
    (1.4, 12, 10.0),
    (1.4, 12, 10.5)
]

def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 1.4, d = 7, W = 6.0
Weight vector (w): [1.4]
Demand vector (d): [7]
Selected fractions (x): [1.]
Total weight in knapsack: 1.4
Total value in knapsack: 7

----------------------------------------
Row 2: w = 1.4, d = 8, W = 6.5
Weight vector (w): [1.4]
Demand vector (d): [8]
Selected fractions (x): [1.]
Total weight in knapsack: 1.4
Total value in knapsack: 8

----------------------------------------
Row 3: w = 1.4, d = 8, W = 7.0
Weight vector (w): [1.4]
Demand vector (d): [8]
Selected fractions (x): [1.]
Total weight in knapsack: 1.4
Total value in knapsack: 8

----------------------------------------
Row 4: w = 1.4, d = 9, W = 7.5
Weight vector (w): [1.4]
Demand vector (d): [9]
Selected fractions (x): [1.]
Total weight in knapsack: 1.4
Total value in knapsack: 9

----------------------------------------
Row 5: w = 1.4, d = 9, W = 8.0
Weight vector (w): [1.4]
Demand vector (d): [9]
Selected fractions (x): [1.]
Total weight in knapsack: 1.4
Total value in knapsack: 9

------

In [2]:
import numpy as np

# Given data for w, d, and W
data = [
    (0.7, 1479, 6.0),
    (0.7, 1603, 6.5),
    (0.7, 1726, 7.0),
    (0.7, 1849, 7.5),
    (0.7, 1972, 8.0),
    (0.7, 2096, 8.5),
    (0.7, 2219, 9.0),
    (0.7, 2342, 9.5),
    (0.7, 2465, 10.0),
    (0.7, 2589, 10.5)
]

def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.7, d = 1479, W = 6.0
Weight vector (w): [0.7]
Demand vector (d): [1479]
Selected fractions (x): [1.]
Total weight in knapsack: 0.7
Total value in knapsack: 1479

----------------------------------------
Row 2: w = 0.7, d = 1603, W = 6.5
Weight vector (w): [0.7]
Demand vector (d): [1603]
Selected fractions (x): [1.]
Total weight in knapsack: 0.7
Total value in knapsack: 1603

----------------------------------------
Row 3: w = 0.7, d = 1726, W = 7.0
Weight vector (w): [0.7]
Demand vector (d): [1726]
Selected fractions (x): [1.]
Total weight in knapsack: 0.7
Total value in knapsack: 1726

----------------------------------------
Row 4: w = 0.7, d = 1849, W = 7.5
Weight vector (w): [0.7]
Demand vector (d): [1849]
Selected fractions (x): [1.]
Total weight in knapsack: 0.7
Total value in knapsack: 1849

----------------------------------------
Row 5: w = 0.7, d = 1972, W = 8.0
Weight vector (w): [0.7]
Demand vector (d): [1972]
Selected fractions (x): [1.]
Total weight in knapsa

In [3]:
import numpy as np

# Given data for w, d, and W
data = [
    (3.41, 93, 6.0),
    (3.41, 101, 6.5),
    (3.41, 108, 7.0),
    (3.41, 116, 7.5),
    (3.41, 124, 8.0),
    (3.41, 132, 8.5),
    (3.41, 139, 9.0),
    (3.41, 147, 9.5),
    (3.41, 155, 10.0),
    (3.41, 163, 10.5)
]
def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.41, d = 93, W = 6.0
Weight vector (w): [3.41]
Demand vector (d): [93]
Selected fractions (x): [1.]
Total weight in knapsack: 3.41
Total value in knapsack: 93

----------------------------------------
Row 2: w = 3.41, d = 101, W = 6.5
Weight vector (w): [3.41]
Demand vector (d): [101]
Selected fractions (x): [1.]
Total weight in knapsack: 3.41
Total value in knapsack: 101

----------------------------------------
Row 3: w = 3.41, d = 108, W = 7.0
Weight vector (w): [3.41]
Demand vector (d): [108]
Selected fractions (x): [1.]
Total weight in knapsack: 3.41
Total value in knapsack: 108

----------------------------------------
Row 4: w = 3.41, d = 116, W = 7.5
Weight vector (w): [3.41]
Demand vector (d): [116]
Selected fractions (x): [1.]
Total weight in knapsack: 3.41
Total value in knapsack: 116

----------------------------------------
Row 5: w = 3.41, d = 124, W = 8.0
Weight vector (w): [3.41]
Demand vector (d): [124]
Selected fractions (x): [1.]
Total weight in knapsack:

In [4]:
import numpy as np

data = [
    (3.98, 63, 6.0),
    (3.98, 67, 6.5),
    (3.98, 72, 7.0),
    (3.98, 77, 7.5),
    (3.98, 83, 8.0),
    (3.98, 88, 8.5),
    (3.98, 93, 9.0),
    (3.98, 98, 9.5),
    (3.98, 103, 10.0),
    (3.98, 108, 10.5)
]
def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.98, d = 63, W = 6.0
Weight vector (w): [3.98]
Demand vector (d): [63]
Selected fractions (x): [1.]
Total weight in knapsack: 3.98
Total value in knapsack: 63

----------------------------------------
Row 2: w = 3.98, d = 67, W = 6.5
Weight vector (w): [3.98]
Demand vector (d): [67]
Selected fractions (x): [1.]
Total weight in knapsack: 3.98
Total value in knapsack: 67

----------------------------------------
Row 3: w = 3.98, d = 72, W = 7.0
Weight vector (w): [3.98]
Demand vector (d): [72]
Selected fractions (x): [1.]
Total weight in knapsack: 3.98
Total value in knapsack: 72

----------------------------------------
Row 4: w = 3.98, d = 77, W = 7.5
Weight vector (w): [3.98]
Demand vector (d): [77]
Selected fractions (x): [1.]
Total weight in knapsack: 3.98
Total value in knapsack: 77

----------------------------------------
Row 5: w = 3.98, d = 83, W = 8.0
Weight vector (w): [3.98]
Demand vector (d): [83]
Selected fractions (x): [1.]
Total weight in knapsack: 3.98
Total

In [5]:
import numpy as np

data = [
    (0.765, 361, 6.0),
    (0.765, 392, 6.5),
    (0.765, 422, 7.0),
    (0.765, 452, 7.5),
    (0.765, 482, 8.0),
    (0.765, 512, 8.5),
    (0.765, 542, 9.0),
    (0.765, 572, 9.5),
    (0.765, 602, 10.0),
    (0.765, 633, 10.5)
]

def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.765, d = 361, W = 6.0
Weight vector (w): [0.765]
Demand vector (d): [361]
Selected fractions (x): [1.]
Total weight in knapsack: 0.765
Total value in knapsack: 361

----------------------------------------
Row 2: w = 0.765, d = 392, W = 6.5
Weight vector (w): [0.765]
Demand vector (d): [392]
Selected fractions (x): [1.]
Total weight in knapsack: 0.765
Total value in knapsack: 392

----------------------------------------
Row 3: w = 0.765, d = 422, W = 7.0
Weight vector (w): [0.765]
Demand vector (d): [422]
Selected fractions (x): [1.]
Total weight in knapsack: 0.765
Total value in knapsack: 422

----------------------------------------
Row 4: w = 0.765, d = 452, W = 7.5
Weight vector (w): [0.765]
Demand vector (d): [452]
Selected fractions (x): [1.]
Total weight in knapsack: 0.765
Total value in knapsack: 452

----------------------------------------
Row 5: w = 0.765, d = 482, W = 8.0
Weight vector (w): [0.765]
Demand vector (d): [482]
Selected fractions (x): [1.]
Total we

In [6]:
import numpy as np

data = [
    (1.13, 289, 6.0),
    (1.13, 313, 6.5),
    (1.13, 337, 7.0),
    (1.13, 361, 7.5),
    (1.13, 386, 8.0),
    (1.13, 410, 8.5),
    (1.13, 434, 9.0),
    (1.13, 458, 9.5),
    (1.13, 482, 10.0),
    (1.13, 506, 10.5)
]

def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 1.13, d = 289, W = 6.0
Weight vector (w): [1.13]
Demand vector (d): [289]
Selected fractions (x): [1.]
Total weight in knapsack: 1.13
Total value in knapsack: 289

----------------------------------------
Row 2: w = 1.13, d = 313, W = 6.5
Weight vector (w): [1.13]
Demand vector (d): [313]
Selected fractions (x): [1.]
Total weight in knapsack: 1.13
Total value in knapsack: 313

----------------------------------------
Row 3: w = 1.13, d = 337, W = 7.0
Weight vector (w): [1.13]
Demand vector (d): [337]
Selected fractions (x): [1.]
Total weight in knapsack: 1.13
Total value in knapsack: 337

----------------------------------------
Row 4: w = 1.13, d = 361, W = 7.5
Weight vector (w): [1.13]
Demand vector (d): [361]
Selected fractions (x): [1.]
Total weight in knapsack: 1.13
Total value in knapsack: 361

----------------------------------------
Row 5: w = 1.13, d = 386, W = 8.0
Weight vector (w): [1.13]
Demand vector (d): [386]
Selected fractions (x): [1.]
Total weight in knapsa

In [7]:
import numpy as np

data = [
    (6.18, 183, 6.0),
    (6.18, 199, 6.5),
    (6.18, 214, 7.0),
    (6.18, 229, 7.5),
    (6.18, 244, 8.0),
    (6.18, 260, 8.5),
    (6.18, 275, 9.0),
    (6.18, 290, 9.5),
    (6.18, 305, 10.0),
    (6.18, 321, 10.5)
]
def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)

    # Greedily add items until we can't add any more
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    # Call the greedy_knapsack function
    x, total_weight, total_value = greedy_knapsack(W, w, d)

    # Print results
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()

# Iterate through each set of w, d, W and solve knapsack problem using greedy approach
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_greedy_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 6.18, d = 183, W = 6.0
Weight vector (w): [6.18]
Demand vector (d): [183]
Selected fractions (x): [0.97087379]
Total weight in knapsack: 6.0
Total value in knapsack: 177.66990291262135

----------------------------------------
Row 2: w = 6.18, d = 199, W = 6.5
Weight vector (w): [6.18]
Demand vector (d): [199]
Selected fractions (x): [1.]
Total weight in knapsack: 6.18
Total value in knapsack: 199

----------------------------------------
Row 3: w = 6.18, d = 214, W = 7.0
Weight vector (w): [6.18]
Demand vector (d): [214]
Selected fractions (x): [1.]
Total weight in knapsack: 6.18
Total value in knapsack: 214

----------------------------------------
Row 4: w = 6.18, d = 229, W = 7.5
Weight vector (w): [6.18]
Demand vector (d): [229]
Selected fractions (x): [1.]
Total weight in knapsack: 6.18
Total value in knapsack: 229

----------------------------------------
Row 5: w = 6.18, d = 244, W = 8.0
Weight vector (w): [6.18]
Demand vector (d): [244]
Selected fractions (x): [1.]


Fulfilled-
#For w=1.4
fulfilled=96/96

#For w=0.7
fulfilled=20340/20340

#For w=3.41
 fulfilled=1278/1278                                       

#For w=3.98
fulfilled=852/852

#For w=0.765
 fulfilled=4970/4970

#For w=1.13
 fulfilled=3976/3976

#For w=6.18
 fulfilled=2515/2520 [on calculating 99.7% effective]




Computing on basis of Knapsack LPP problem

Individually iteration of each width and sol.x to get the matrix row by row -



In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (1.4, 7, 6.0),
    (1.4, 8, 6.5),
    (1.4, 8, 7.0),
    (1.4, 9, 7.5),
    (1.4, 9, 8.0),
    (1.4, 10, 8.5),
    (1.4, 10, 9.0),
    (1.4, 11, 9.5),
    (1.4, 12, 10.0),
    (1.4, 12, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 1.4, d = 7, W = 6.0
A matrix:
[[4.]]

sol.x:
[1.75]

----------------------------------------
Row 2: w = 1.4, d = 8, W = 6.5
A matrix:
[[4.]]

sol.x:
[2.]

----------------------------------------
Row 3: w = 1.4, d = 8, W = 7.0
A matrix:
[[5.]]

sol.x:
[1.6]

----------------------------------------
Row 4: w = 1.4, d = 9, W = 7.5
A matrix:
[[5.]]

sol.x:
[1.8]

----------------------------------------
Row 5: w = 1.4, d = 9, W = 8.0
A matrix:
[[5.]]

sol.x:
[1.8]

----------------------------------------
Row 6: w = 1.4, d = 10, W = 8.5
A matrix:
[[6.]]

sol.x:
[1.66666667]

----------------------------------------
Row 7: w = 1.4, d = 10, W = 9.0
A matrix:
[[6.]]

sol.x:
[1.66666667]

----------------------------------------
Row 8: w = 1.4, d = 11, W = 9.5
A matrix:
[[6.]]

sol.x:
[1.83333333]

----------------------------------------
Row 9: w = 1.4, d = 12, W = 10.0
A matrix:
[[7.]]

sol.x:
[1.71428571]

----------------------------------------
Row 10: w = 1.4, d = 12, W = 10

#For w=1.4
A=[4,4,5,5,5,6,6,6,7,7]   
sol.x=[1.75,2,1.6,1.8,1.8,1.66,1.66,1.83,1.714,1.714]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (0.7, 1479, 6.0),
    (0.7, 1603, 6.5),
    (0.7, 1726, 7.0),
    (0.7, 1849, 7.5),
    (0.7, 1972, 8.0),
    (0.7, 2096, 8.5),
    (0.7, 2219, 9.0),
    (0.7, 2342, 9.5),
    (0.7, 2465, 10.0),
    (0.7, 2589, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.7, d = 1479, W = 6.0
A matrix:
[[8.]]

sol.x:
[184.875]

----------------------------------------
Row 2: w = 0.7, d = 1603, W = 6.5
A matrix:
[[9.]]

sol.x:
[178.11111111]

----------------------------------------
Row 3: w = 0.7, d = 1726, W = 7.0
A matrix:
[[10.]]

sol.x:
[172.6]

----------------------------------------
Row 4: w = 0.7, d = 1849, W = 7.5
A matrix:
[[10.]]

sol.x:
[184.9]

----------------------------------------
Row 5: w = 0.7, d = 1972, W = 8.0
A matrix:
[[11.]]

sol.x:
[179.27272727]

----------------------------------------
Row 6: w = 0.7, d = 2096, W = 8.5
A matrix:
[[12.]]

sol.x:
[174.66666667]

----------------------------------------
Row 7: w = 0.7, d = 2219, W = 9.0
A matrix:
[[12.]]

sol.x:
[184.91666667]

----------------------------------------
Row 8: w = 0.7, d = 2342, W = 9.5
A matrix:
[[13.]]

sol.x:
[180.15384615]

----------------------------------------
Row 9: w = 0.7, d = 2465, W = 10.0
A matrix:
[[14.]]

sol.x:
[176.07142857]

--------

#For w=0.7
A=[8,9,10,10,11,12,12,13,14,15]   
sol.x=[184.87,178.11,172.6,184.9,179.27,174.67,184.91,180.15,176.07,172.6]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (3.41, 93, 6.0),
    (3.41, 101, 6.5),
    (3.41, 108, 7.0),
    (3.41, 116, 7.5),
    (3.41, 124, 8.0),
    (3.41, 132, 8.5),
    (3.41, 139, 9.0),
    (3.41, 147, 9.5),
    (3.41, 155, 10.0),
    (3.41, 163, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.41, d = 93, W = 6.0
A matrix:
[[1.]]

sol.x:
[93.]

----------------------------------------
Row 2: w = 3.41, d = 101, W = 6.5
A matrix:
[[1.]]

sol.x:
[101.]

----------------------------------------
Row 3: w = 3.41, d = 108, W = 7.0
A matrix:
[[2.]]

sol.x:
[54.]

----------------------------------------
Row 4: w = 3.41, d = 116, W = 7.5
A matrix:
[[2.]]

sol.x:
[58.]

----------------------------------------
Row 5: w = 3.41, d = 124, W = 8.0
A matrix:
[[2.]]

sol.x:
[62.]

----------------------------------------
Row 6: w = 3.41, d = 132, W = 8.5
A matrix:
[[2.]]

sol.x:
[66.]

----------------------------------------
Row 7: w = 3.41, d = 139, W = 9.0
A matrix:
[[2.]]

sol.x:
[69.5]

----------------------------------------
Row 8: w = 3.41, d = 147, W = 9.5
A matrix:
[[2.]]

sol.x:
[73.5]

----------------------------------------
Row 9: w = 3.41, d = 155, W = 10.0
A matrix:
[[2.]]

sol.x:
[77.5]

----------------------------------------
Row 10: w = 3.41, d = 163, W = 10

#for w=3.41
A=[1,1,2,2,2,2,2,2,2,3]    
sol.x=[93,101,54,58,62,66,69.5,73.5,77.5,54.33]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (3.98, 63, 6.0),
    (3.98, 67, 6.5),
    (3.98, 72, 7.0),
    (3.98, 77, 7.5),
    (3.98, 83, 8.0),
    (3.98, 88, 8.5),
    (3.98, 93, 9.0),
    (3.98, 98, 9.5),
    (3.98, 103, 10.0),
    (3.98, 108, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.98, d = 63, W = 6.0
A matrix:
[[1.]]

sol.x:
[63.]

----------------------------------------
Row 2: w = 3.98, d = 67, W = 6.5
A matrix:
[[1.]]

sol.x:
[67.]

----------------------------------------
Row 3: w = 3.98, d = 72, W = 7.0
A matrix:
[[1.]]

sol.x:
[72.]

----------------------------------------
Row 4: w = 3.98, d = 77, W = 7.5
A matrix:
[[1.]]

sol.x:
[77.]

----------------------------------------
Row 5: w = 3.98, d = 83, W = 8.0
A matrix:
[[2.]]

sol.x:
[41.5]

----------------------------------------
Row 6: w = 3.98, d = 88, W = 8.5
A matrix:
[[2.]]

sol.x:
[44.]

----------------------------------------
Row 7: w = 3.98, d = 93, W = 9.0
A matrix:
[[2.]]

sol.x:
[46.5]

----------------------------------------
Row 8: w = 3.98, d = 98, W = 9.5
A matrix:
[[2.]]

sol.x:
[49.]

----------------------------------------
Row 9: w = 3.98, d = 103, W = 10.0
A matrix:
[[2.]]

sol.x:
[51.5]

----------------------------------------
Row 10: w = 3.98, d = 108, W = 10.5
A mat

#For w=3.98
A=[1,1,1,1,2,2,2,2,2,2]   
sol.x=[63,67,72,77,41.5,44,46.5,49,51.5,54]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (0.765, 361, 6.0),
    (0.765, 392, 6.5),
    (0.765, 422, 7.0),
    (0.765, 452, 7.5),
    (0.765, 482, 8.0),
    (0.765, 512, 8.5),
    (0.765, 542, 9.0),
    (0.765, 572, 9.5),
    (0.765, 602, 10.0),
    (0.765, 633, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.765, d = 361, W = 6.0
A matrix:
[[7.]]

sol.x:
[51.57142857]

----------------------------------------
Row 2: w = 0.765, d = 392, W = 6.5
A matrix:
[[8.]]

sol.x:
[49.]

----------------------------------------
Row 3: w = 0.765, d = 422, W = 7.0
A matrix:
[[9.]]

sol.x:
[46.88888889]

----------------------------------------
Row 4: w = 0.765, d = 452, W = 7.5
A matrix:
[[9.]]

sol.x:
[50.22222222]

----------------------------------------
Row 5: w = 0.765, d = 482, W = 8.0
A matrix:
[[10.]]

sol.x:
[48.2]

----------------------------------------
Row 6: w = 0.765, d = 512, W = 8.5
A matrix:
[[11.]]

sol.x:
[46.54545455]

----------------------------------------
Row 7: w = 0.765, d = 542, W = 9.0
A matrix:
[[11.]]

sol.x:
[49.27272727]

----------------------------------------
Row 8: w = 0.765, d = 572, W = 9.5
A matrix:
[[12.]]

sol.x:
[47.66666667]

----------------------------------------
Row 9: w = 0.765, d = 602, W = 10.0
A matrix:
[[13.]]

sol.x:
[46.30769231]

------

#For w=0.765
A=[7,8,9,9,10,11,11,12,13,13]   
sol.x=[51.57,49,46.88,50.22,48.2,46.54,49.27,47.66,46.30,48.64]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (1.13, 289, 6.0),
    (1.13, 313, 6.5),
    (1.13, 337, 7.0),
    (1.13, 361, 7.5),
    (1.13, 386, 8.0),
    (1.13, 410, 8.5),
    (1.13, 434, 9.0),
    (1.13, 458, 9.5),
    (1.13, 482, 10.0),
    (1.13, 506, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 1.13, d = 289, W = 6.0
A matrix:
[[5.]]

sol.x:
[57.8]

----------------------------------------
Row 2: w = 1.13, d = 313, W = 6.5
A matrix:
[[5.]]

sol.x:
[62.6]

----------------------------------------
Row 3: w = 1.13, d = 337, W = 7.0
A matrix:
[[6.]]

sol.x:
[56.16666667]

----------------------------------------
Row 4: w = 1.13, d = 361, W = 7.5
A matrix:
[[6.]]

sol.x:
[60.16666667]

----------------------------------------
Row 5: w = 1.13, d = 386, W = 8.0
A matrix:
[[7.]]

sol.x:
[55.14285714]

----------------------------------------
Row 6: w = 1.13, d = 410, W = 8.5
A matrix:
[[7.]]

sol.x:
[58.57142857]

----------------------------------------
Row 7: w = 1.13, d = 434, W = 9.0
A matrix:
[[7.]]

sol.x:
[62.]

----------------------------------------
Row 8: w = 1.13, d = 458, W = 9.5
A matrix:
[[8.]]

sol.x:
[57.25]

----------------------------------------
Row 9: w = 1.13, d = 482, W = 10.0
A matrix:
[[8.]]

sol.x:
[60.25]

---------------------------------------

#For w=1.13
A=[5,5,6,6,7,7,7,8,8,9]   
sol.x=[57.8,62.6,56.16,60.16,55.14,58.57,62,57.25,60.25,56.22]

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (6.18, 183, 6.0),
    (6.18, 199, 6.5),
    (6.18, 214, 7.0),
    (6.18, 229, 7.5),
    (6.18, 244, 8.0),
    (6.18, 260, 8.5),
    (6.18, 275, 9.0),
    (6.18, 290, 9.5),
    (6.18, 305, 10.0),
    (6.18, 321, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 6.18, d = 183, W = 6.0
A matrix:
[[0.]]

sol.x:
None

----------------------------------------
Row 2: w = 6.18, d = 199, W = 6.5
A matrix:
[[1.]]

sol.x:
[199.]

----------------------------------------
Row 3: w = 6.18, d = 214, W = 7.0
A matrix:
[[1.]]

sol.x:
[214.]

----------------------------------------
Row 4: w = 6.18, d = 229, W = 7.5
A matrix:
[[1.]]

sol.x:
[229.]

----------------------------------------
Row 5: w = 6.18, d = 244, W = 8.0
A matrix:
[[1.]]

sol.x:
[244.]

----------------------------------------
Row 6: w = 6.18, d = 260, W = 8.5
A matrix:
[[1.]]

sol.x:
[260.]

----------------------------------------
Row 7: w = 6.18, d = 275, W = 9.0
A matrix:
[[1.]]

sol.x:
[275.]

----------------------------------------
Row 8: w = 6.18, d = 290, W = 9.5
A matrix:
[[1.]]

sol.x:
[290.]

----------------------------------------
Row 9: w = 6.18, d = 305, W = 10.0
A matrix:
[[1.]]

sol.x:
[305.]

----------------------------------------
Row 10: w = 6.18, d = 321, W 

#For w=6.18
A=[0,1,1,1,1,1,1,1,1,1]    
sol.x=[0,199,214,229,244,260,275,290,305,321]

FINAL A-(Combining all)

In [ ]:
[[ 4.,  8.,  1.,  1.,  7.,  5., 0.],
  [ 4.,  9.,  1.,  1.,  8.,  5., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  11.,  2.,  2.,  10.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  13.,  2.,  2.,  12.,  8., 1.],
  [ 7.,  14.,  2.,  2.,  13.,  8., 1.],
  [ 7.,  15.,  3.,  2.,  13.,  9., 1.]]


#For w=1.4
fullfilled=95.89/96
#For w=0.7
 fullfilled=20338.9/20340
#for w=3.41
 fullfilled=1277.99/1278
#For w=3.98
fullfilled=852/852
#For w=1.13
 fullfilled=3975.87/3976
#For w=6.18
fulfilled=2337/2520

In [ ]:
#FINAL COMBINING ALL -A MATRIX-
[[ 4.,  8.,  1.,  1.,  7.,  5., 0.],
  [ 4.,  9.,  1.,  1.,  8.,  5., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  11.,  2.,  2.,  10.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  13.,  2.,  2.,  12.,  8., 1.],
  [ 7.,  14.,  2.,  2.,  13.,  8., 1.],
  [ 7.,  15.,  3.,  2.,  13.,  9., 1.]]


Distribution of demands by using Genetic Algorithm

In [ ]:
import numpy as np

# Genetic Algorithm Parameters
POPULATION_SIZE = 100
NUM_GENERATIONS = 200
MUTATION_RATE = 0.05

def fitness(solution, d, W):
    total_demand = np.sum(solution)
    if total_demand != d:
        return -np.inf
    total_weight = np.sum(np.array(solution) * np.array(W))
    return -total_weight

# Initialize population
def initialize_population(population_size, num_weights):
    population = []
    for _ in range(population_size):
        chromosome = np.random.randint(0, 10, size=num_weights)
        population.append(chromosome)
    return np.array(population)

# Selection: Tournament selection
def tournament_selection(population, fitness_values, tournament_size=3):
    idx = np.random.choice(len(population), tournament_size, replace=False)
    tournament_fitness = fitness_values[idx]
    return population[idx[np.argmax(tournament_fitness)]]

# Crossover: Single point crossover
def crossover(parent1, parent2):
    crossover_point = np.random.randint(len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return child1, child2

# Mutation: Bit flip mutation
def mutate(solution, mutation_rate, max_value):
    mutated_solution = solution.copy()
    for i in range(len(mutated_solution)):
        if np.random.rand() < mutation_rate:
            mutated_solution[i] = np.random.randint(0, max_value + 1)
    return mutated_solution

# Genetic Algorithm
def genetic_algorithm(d, W):
    population = initialize_population(POPULATION_SIZE, len(W))
    max_value = int(np.ceil(d / min(W)))

    for generation in range(NUM_GENERATIONS):
        fitness_values = np.array([fitness(individual, d, W) for individual in population])
        new_population = []
        for _ in range(POPULATION_SIZE // 2):
            parents = [tournament_selection(population, fitness_values) for _ in range(2)]
            offspring1, offspring2 = crossover(parents[0], parents[1])
            offspring1 = mutate(offspring1, MUTATION_RATE, max_value)
            offspring2 = mutate(offspring2, MUTATION_RATE, max_value)
            new_population.extend([offspring1, offspring2])
        population = np.array(new_population)

    fitness_values = np.array([fitness(individual, d, W) for individual in population])
    best_solution_idx = np.argmax(fitness_values)
    best_solution = population[best_solution_idx]
    total_weight = np.sum(np.array(best_solution) * np.array(W))

    return best_solution, total_weight

# Solve the demand distribution problem using genetic algorithm
data = {
    "w": [1.4, 0.7, 3.41, 3.98, 0.765, 1.13, 6.18],
    "d": [96, 20340, 1278, 852, 4970, 3976, 2520],
    "W": [6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5]
}

formatted_results = []

for i in range(len(data['w'])):
    w = data['w'][i]
    d_value = data['d'][i]
    best_solution, total_weight = genetic_algorithm(d_value, data['W'])

    for j, W_value in enumerate(data['W']):
        if best_solution[j] > 0:
            formatted_results.append(f"{w}\t{best_solution[j]}\t{W_value}")

for result in formatted_results:
    print(result)


1.4	14	6.0
1.4	8	6.5
1.4	9	7.0
1.4	4	7.5
1.4	9	8.0
1.4	9	8.5
1.4	8	9.0
1.4	16	9.5
1.4	7	10.0
1.4	12	10.5
0.7	1665	6.0
0.7	513	6.5
0.7	883	7.0
0.7	395	7.5
0.7	1860	8.0
0.7	2366	8.5
0.7	3123	9.0
0.7	2682	9.5
0.7	923	10.0
0.7	2251	10.5
3.41	83	6.0
3.41	12	6.5
3.41	13	7.0
3.41	3	7.5
3.41	91	8.0
3.41	160	8.5
3.41	126	9.0
3.41	59	9.5
3.41	191	10.0
3.41	32	10.5
3.98	38	6.0
3.98	49	6.5
3.98	2	7.0
3.98	118	7.5
3.98	47	8.0
3.98	51	8.5
3.98	82	9.0
3.98	51	9.5
3.98	106	10.0
3.98	128	10.5
0.765	654	6.0
0.765	399	6.5
0.765	737	7.0
0.765	21	7.5
0.765	348	8.0
0.765	417	8.5
0.765	755	9.0
0.765	518	9.5
0.765	635	10.0
0.765	632	10.5
1.13	433	6.0
1.13	410	6.5
1.13	148	7.0
1.13	392	7.5
1.13	437	8.0
1.13	388	8.5
1.13	470	9.0
1.13	650	9.5
1.13	252	10.0
1.13	528	10.5
6.18	30	6.0
6.18	266	6.5
6.18	338	7.0
6.18	150	7.5
6.18	244	8.0
6.18	28	8.5
6.18	13	9.0
6.18	396	9.5
6.18	184	10.0
6.18	416	10.5


Calculating Matrix and sol.x on basis of Genetic Algorithm Demand Distribution

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (1.4, 12, 6.0),
    (1.4, 14, 6.5),
    (1.4, 5, 7.0),
    (1.4, 16, 7.5),
    (1.4, 10, 8.0),
    (1.4, 8, 8.5),
    (1.4, 12, 9.0),
    (1.4, 7, 9.5),
    (1.4, 7, 10.0),
    (1.4, 5, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 1.4, d = 12, W = 6.0
A matrix:
[[4.]]

sol.x:
[3.]

----------------------------------------
Row 2: w = 1.4, d = 14, W = 6.5
A matrix:
[[4.]]

sol.x:
[3.5]

----------------------------------------
Row 3: w = 1.4, d = 5, W = 7.0
A matrix:
[[5.]]

sol.x:
[1.]

----------------------------------------
Row 4: w = 1.4, d = 16, W = 7.5
A matrix:
[[5.]]

sol.x:
[3.2]

----------------------------------------
Row 5: w = 1.4, d = 10, W = 8.0
A matrix:
[[5.]]

sol.x:
[2.]

----------------------------------------
Row 6: w = 1.4, d = 8, W = 8.5
A matrix:
[[6.]]

sol.x:
[1.33333333]

----------------------------------------
Row 7: w = 1.4, d = 12, W = 9.0
A matrix:
[[6.]]

sol.x:
[2.]

----------------------------------------
Row 8: w = 1.4, d = 7, W = 9.5
A matrix:
[[6.]]

sol.x:
[1.16666667]

----------------------------------------
Row 9: w = 1.4, d = 7, W = 10.0
A matrix:
[[7.]]

sol.x:
[1.]

----------------------------------------
Row 10: w = 1.4, d = 5, W = 10.5
A matrix:
[[7.]]

#For w=1.4
fullfilled=95.93/96

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (0.7, 2789, 6.0),
    (0.7, 12, 6.5),
    (0.7, 2983, 7.0),
    (0.7, 1009, 7.5),
    (0.7, 873, 8.0),
    (0.7, 1166, 8.5),
    (0.7, 3335, 9.0),
    (0.7, 2217, 9.5),
    (0.7, 2289, 10.0),
    (0.7, 2748, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.7, d = 2789, W = 6.0
A matrix:
[[8.]]

sol.x:
[348.625]

----------------------------------------
Row 2: w = 0.7, d = 12, W = 6.5
A matrix:
[[9.]]

sol.x:
[1.33333333]

----------------------------------------
Row 3: w = 0.7, d = 2983, W = 7.0
A matrix:
[[10.]]

sol.x:
[298.3]

----------------------------------------
Row 4: w = 0.7, d = 1009, W = 7.5
A matrix:
[[10.]]

sol.x:
[100.9]

----------------------------------------
Row 5: w = 0.7, d = 873, W = 8.0
A matrix:
[[11.]]

sol.x:
[79.36363636]

----------------------------------------
Row 6: w = 0.7, d = 1166, W = 8.5
A matrix:
[[12.]]

sol.x:
[97.16666667]

----------------------------------------
Row 7: w = 0.7, d = 3335, W = 9.0
A matrix:
[[12.]]

sol.x:
[277.91666667]

----------------------------------------
Row 8: w = 0.7, d = 2217, W = 9.5
A matrix:
[[13.]]

sol.x:
[170.53846154]

----------------------------------------
Row 9: w = 0.7, d = 2289, W = 10.0
A matrix:
[[14.]]

sol.x:
[163.5]

----------------------

#For w=0.7
fullfilled=19421/20340

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (3.41, 57, 6.0),
    (3.41, 171, 6.5),
    (3.41, 158, 7.0),
    (3.41, 185, 7.5),
    (3.41, 107, 8.0),
    (3.41, 208, 8.5),
    (3.41, 52, 9.0),
    (3.41, 31, 9.5),
    (3.41, 185, 10.0),
    (3.41, 124, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.41, d = 57, W = 6.0
A matrix:
[[1.]]

sol.x:
[57.]

----------------------------------------
Row 2: w = 3.41, d = 171, W = 6.5
A matrix:
[[1.]]

sol.x:
[171.]

----------------------------------------
Row 3: w = 3.41, d = 158, W = 7.0
A matrix:
[[2.]]

sol.x:
[79.]

----------------------------------------
Row 4: w = 3.41, d = 185, W = 7.5
A matrix:
[[2.]]

sol.x:
[92.5]

----------------------------------------
Row 5: w = 3.41, d = 107, W = 8.0
A matrix:
[[2.]]

sol.x:
[53.5]

----------------------------------------
Row 6: w = 3.41, d = 208, W = 8.5
A matrix:
[[2.]]

sol.x:
[104.]

----------------------------------------
Row 7: w = 3.41, d = 52, W = 9.0
A matrix:
[[2.]]

sol.x:
[26.]

----------------------------------------
Row 8: w = 3.41, d = 31, W = 9.5
A matrix:
[[2.]]

sol.x:
[15.5]

----------------------------------------
Row 9: w = 3.41, d = 185, W = 10.0
A matrix:
[[2.]]

sol.x:
[92.5]

----------------------------------------
Row 10: w = 3.41, d = 124, W = 10

#For w=3.41
fullfilled=1277.9/1278

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (3.98, 19, 6.0),
    (3.98, 113, 6.5),
    (3.98, 134, 7.0),
    (3.98, 99, 7.5),
    (3.98, 51, 8.0),
    (3.98, 119, 8.5),
    (3.98, 39, 9.0),
    (3.98, 72, 9.5),
    (3.98, 103, 10.0),
    (3.98, 78, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 3.98, d = 19, W = 6.0
A matrix:
[[1.]]

sol.x:
[19.]

----------------------------------------
Row 2: w = 3.98, d = 113, W = 6.5
A matrix:
[[1.]]

sol.x:
[113.]

----------------------------------------
Row 3: w = 3.98, d = 134, W = 7.0
A matrix:
[[1.]]

sol.x:
[134.]

----------------------------------------
Row 4: w = 3.98, d = 99, W = 7.5
A matrix:
[[1.]]

sol.x:
[99.]

----------------------------------------
Row 5: w = 3.98, d = 51, W = 8.0
A matrix:
[[2.]]

sol.x:
[25.5]

----------------------------------------
Row 6: w = 3.98, d = 119, W = 8.5
A matrix:
[[2.]]

sol.x:
[59.5]

----------------------------------------
Row 7: w = 3.98, d = 39, W = 9.0
A matrix:
[[2.]]

sol.x:
[19.5]

----------------------------------------
Row 8: w = 3.98, d = 72, W = 9.5
A matrix:
[[2.]]

sol.x:
[36.]

----------------------------------------
Row 9: w = 3.98, d = 103, W = 10.0
A matrix:
[[2.]]

sol.x:
[51.5]

----------------------------------------
Row 10: w = 3.98, d = 78, W = 10.5


#For w=3.98
fullfilled=827/827

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (0.765, 566, 6.0),
    (0.765, 199, 6.5),
    (0.765, 237, 7.0),
    (0.765, 430, 7.5),
    (0.765, 139, 8.0),
    (0.765, 291, 8.5),
    (0.765, 402, 9.0),
    (0.765, 568, 9.5),
    (0.765, 123, 10.0),
    (0.765, 371, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 0.765, d = 566, W = 6.0
A matrix:
[[7.]]

sol.x:
[80.85714286]

----------------------------------------
Row 2: w = 0.765, d = 199, W = 6.5
A matrix:
[[8.]]

sol.x:
[24.875]

----------------------------------------
Row 3: w = 0.765, d = 237, W = 7.0
A matrix:
[[9.]]

sol.x:
[26.33333333]

----------------------------------------
Row 4: w = 0.765, d = 430, W = 7.5
A matrix:
[[9.]]

sol.x:
[47.77777778]

----------------------------------------
Row 5: w = 0.765, d = 139, W = 8.0
A matrix:
[[10.]]

sol.x:
[13.9]

----------------------------------------
Row 6: w = 0.765, d = 291, W = 8.5
A matrix:
[[11.]]

sol.x:
[26.45454545]

----------------------------------------
Row 7: w = 0.765, d = 402, W = 9.0
A matrix:
[[11.]]

sol.x:
[36.54545455]

----------------------------------------
Row 8: w = 0.765, d = 568, W = 9.5
A matrix:
[[12.]]

sol.x:
[47.33333333]

----------------------------------------
Row 9: w = 0.765, d = 123, W = 10.0
A matrix:
[[13.]]

sol.x:
[9.46153846]

----

#For w=0.765
3325.57/4970

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (1.13, 92, 6.0),
    (1.13, 252, 6.5),
    (1.13, 642, 7.0),
    (1.13, 35, 7.5),
    (1.13, 402, 8.0),
    (1.13,330, 8.5),
    (1.13, 494, 9.0),
    (1.13, 108, 9.5),
    (1.13, 64, 10.0),
    (1.13, 3, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)
''

Row 1: w = 1.13, d = 92, W = 6.0
A matrix:
[[5.]]

sol.x:
[18.4]

----------------------------------------
Row 2: w = 1.13, d = 252, W = 6.5
A matrix:
[[5.]]

sol.x:
[50.4]

----------------------------------------
Row 3: w = 1.13, d = 642, W = 7.0
A matrix:
[[6.]]

sol.x:
[107.]

----------------------------------------
Row 4: w = 1.13, d = 35, W = 7.5
A matrix:
[[6.]]

sol.x:
[5.83333333]

----------------------------------------
Row 5: w = 1.13, d = 402, W = 8.0
A matrix:
[[7.]]

sol.x:
[57.42857143]

----------------------------------------
Row 6: w = 1.13, d = 330, W = 8.5
A matrix:
[[7.]]

sol.x:
[47.14285714]

----------------------------------------
Row 7: w = 1.13, d = 494, W = 9.0
A matrix:
[[7.]]

sol.x:
[70.57142857]

----------------------------------------
Row 8: w = 1.13, d = 108, W = 9.5
A matrix:
[[8.]]

sol.x:
[13.5]

----------------------------------------
Row 9: w = 1.13, d = 64, W = 10.0
A matrix:
[[8.]]

sol.x:
[8.]

----------------------------------------
Row 1

''

#For w=1.13
fullfilled=2421/3976

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Given data for w, d, and W
data = [
    (6.18, 181, 6.0),
    (6.18, 269, 6.5),
    (6.18, 365, 7.0),
    (6.18, 149, 7.5),
    (6.18, 230, 8.0),
    (6.18, 292, 8.5),
    (6.18, 276, 9.0),
    (6.18, 278, 9.5),
    (6.18, 119, 10.0),
    (6.18, 86, 10.5)
]

def solve_knapsack(W, w, duals):
    res = linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')
    return res

def generate_optimal_pattern(W, w, d):
    # Convert w and d to numpy arrays to ensure they are iterable
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)  # Initialize A matrix with a feasible solution
    c = np.ones(len(w))  # Objective function to maximize number of items

    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    # Print A matrix
    print("A matrix:")
    print(A)
    print()

    # Print sol.x
    print("sol.x:")
    print(sol.x)
    print()

# Iterate through each set of w, d, W and solve knapsack problem
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
    generate_optimal_pattern(W, [w], [d])  # Pass w and d as lists
    print("-" * 40)


Row 1: w = 6.18, d = 181, W = 6.0
A matrix:
[[0.]]

sol.x:
None

----------------------------------------
Row 2: w = 6.18, d = 269, W = 6.5
A matrix:
[[1.]]

sol.x:
[269.]

----------------------------------------
Row 3: w = 6.18, d = 365, W = 7.0
A matrix:
[[1.]]

sol.x:
[365.]

----------------------------------------
Row 4: w = 6.18, d = 149, W = 7.5
A matrix:
[[1.]]

sol.x:
[149.]

----------------------------------------
Row 5: w = 6.18, d = 230, W = 8.0
A matrix:
[[1.]]

sol.x:
[230.]

----------------------------------------
Row 6: w = 6.18, d = 292, W = 8.5
A matrix:
[[1.]]

sol.x:
[292.]

----------------------------------------
Row 7: w = 6.18, d = 276, W = 9.0
A matrix:
[[1.]]

sol.x:
[276.]

----------------------------------------
Row 8: w = 6.18, d = 278, W = 9.5
A matrix:
[[1.]]

sol.x:
[278.]

----------------------------------------
Row 9: w = 6.18, d = 119, W = 10.0
A matrix:
[[1.]]

sol.x:
[119.]

----------------------------------------
Row 10: w = 6.18, d = 86, W =

#For w=6.18
Fullfilled=2064/2520

In [ ]:
#FINAL COMBINING ALL -A MATRIX-
[[ 4.,  8.,  1.,  1.,  7.,  5., 0.],
  [ 4.,  9.,  1.,  1.,  8.,  5., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  10.,  2.,  1.,  9.,  6., 1.],
  [ 5.,  11.,  2.,  2.,  10.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  12.,  2.,  2.,  11.,  7., 1.],
  [ 6.,  13.,  2.,  2.,  12.,  8., 1.],
  [ 7.,  14.,  2.,  2.,  13.,  8., 1.],
  [ 7.,  15.,  3.,  2.,  13.,  9., 1.]]


Calculating Demand fullfillment according to knapsack DP Approach(optimal and sol.x)

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (1.4, 7, 6.0),
    (1.4, 8, 6.5),
    (1.4, 8, 7.0),
    (1.4, 9, 7.5),
    (1.4, 9, 8.0),
    (1.4, 10, 8.5),
    (1.4, 10, 9.0),
    (1.4, 11, 9.5),
    (1.4, 12, 10.0),
    (1.4, 12, 10.5)
]

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 1.4, d = 7, W = 6.0
DP Table:
[[0 0 0 0 0 0 0]
 [0 7 7 7 7 7 7]]

sol.x: [1]
Optimal value: 7
----------------------------------------
Row 2: w = 1.4, d = 8, W = 6.5
DP Table:
[[0 0 0 0 0 0 0]
 [0 8 8 8 8 8 8]]

sol.x: [1]
Optimal value: 8
----------------------------------------
Row 3: w = 1.4, d = 8, W = 7.0
DP Table:
[[0 0 0 0 0 0 0 0]
 [0 8 8 8 8 8 8 8]]

sol.x: [1]
Optimal value: 8
----------------------------------------
Row 4: w = 1.4, d = 9, W = 7.5
DP Table:
[[0 0 0 0 0 0 0 0]
 [0 9 9 9 9 9 9 9]]

sol.x: [1]
Optimal value: 9
----------------------------------------
Row 5: w = 1.4, d = 9, W = 8.0
DP Table:
[[0 0 0 0 0 0 0 0 0]
 [0 9 9 9 9 9 9 9 9]]

sol.x: [1]
Optimal value: 9
----------------------------------------
Row 6: w = 1.4, d = 10, W = 8.5
DP Table:
[[ 0  0  0  0  0  0  0  0  0]
 [ 0 10 10 10 10 10 10 10 10]]

sol.x: [1]
Optimal value: 10
----------------------------------------
Row 7: w = 1.4, d = 10, W = 9.0
DP Table:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 

#w=1.4
Fullfilled=86/96

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (0.7, 1479, 6.0),
    (0.7, 1603, 6.5),
    (0.7, 1726, 7.0),
    (0.7, 1849, 7.5),
    (0.7, 1972, 8.0),
    (0.7, 2096, 8.5),
    (0.7, 2219, 9.0),
    (0.7, 2342, 9.5),
    (0.7, 2465, 10.0),
    (0.7, 2589, 10.5)
]
def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 0.7, d = 1479, W = 6.0
DP Table:
[[   0    0    0    0    0    0    0]
 [   0 1479 1479 1479 1479 1479 1479]]

sol.x: [1]
Optimal value: 1479
----------------------------------------
Row 2: w = 0.7, d = 1603, W = 6.5
DP Table:
[[   0    0    0    0    0    0    0]
 [   0 1603 1603 1603 1603 1603 1603]]

sol.x: [1]
Optimal value: 1603
----------------------------------------
Row 3: w = 0.7, d = 1726, W = 7.0
DP Table:
[[   0    0    0    0    0    0    0    0]
 [   0 1726 1726 1726 1726 1726 1726 1726]]

sol.x: [1]
Optimal value: 1726
----------------------------------------
Row 4: w = 0.7, d = 1849, W = 7.5
DP Table:
[[   0    0    0    0    0    0    0    0]
 [   0 1849 1849 1849 1849 1849 1849 1849]]

sol.x: [1]
Optimal value: 1849
----------------------------------------
Row 5: w = 0.7, d = 1972, W = 8.0
DP Table:
[[   0    0    0    0    0    0    0    0    0]
 [   0 1972 1972 1972 1972 1972 1972 1972 1972]]

sol.x: [1]
Optimal value: 1972
-------------------------------

#w=0.7
Fullfilled=20340/20340

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (3.41, 93, 6.0),
    (3.41, 101, 6.5),
    (3.41, 108, 7.0),
    (3.41, 116, 7.5),
    (3.41, 124, 8.0),
    (3.41, 132, 8.5),
    (3.41, 139, 9.0),
    (3.41, 147, 9.5),
    (3.41, 155, 10.0),
    (3.41, 163, 10.5)
]

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 3.41, d = 93, W = 6.0
DP Table:
[[ 0  0  0  0  0  0  0]
 [ 0  0  0 93 93 93 93]]

sol.x: [1]
Optimal value: 93
----------------------------------------
Row 2: w = 3.41, d = 101, W = 6.5
DP Table:
[[  0   0   0   0   0   0   0]
 [  0   0   0 101 101 101 101]]

sol.x: [1]
Optimal value: 101
----------------------------------------
Row 3: w = 3.41, d = 108, W = 7.0
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0   0   0 108 108 108 108 108]]

sol.x: [1]
Optimal value: 108
----------------------------------------
Row 4: w = 3.41, d = 116, W = 7.5
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0   0   0 116 116 116 116 116]]

sol.x: [1]
Optimal value: 116
----------------------------------------
Row 5: w = 3.41, d = 124, W = 8.0
DP Table:
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0 124 124 124 124 124 124]]

sol.x: [1]
Optimal value: 124
----------------------------------------
Row 6: w = 3.41, d = 132, W = 8.5
DP Table:
[[  0   0   0   0   0   0   0   0   0]
 [  0 

#w=3.41
Fullfilled=1278/1278

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (3.98, 63, 6.0),
    (3.98, 67, 6.5),
    (3.98, 72, 7.0),
    (3.98, 77, 7.5),
    (3.98, 83, 8.0),
    (3.98, 88, 8.5),
    (3.98, 93, 9.0),
    (3.98, 98, 9.5),
    (3.98, 103, 10.0),
    (3.98, 108, 10.5)
]

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 3.98, d = 63, W = 6.0
DP Table:
[[ 0  0  0  0  0  0  0]
 [ 0  0  0 63 63 63 63]]

sol.x: [1]
Optimal value: 63
----------------------------------------
Row 2: w = 3.98, d = 67, W = 6.5
DP Table:
[[ 0  0  0  0  0  0  0]
 [ 0  0  0 67 67 67 67]]

sol.x: [1]
Optimal value: 67
----------------------------------------
Row 3: w = 3.98, d = 72, W = 7.0
DP Table:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0 72 72 72 72 72]]

sol.x: [1]
Optimal value: 72
----------------------------------------
Row 4: w = 3.98, d = 77, W = 7.5
DP Table:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0 77 77 77 77 77]]

sol.x: [1]
Optimal value: 77
----------------------------------------
Row 5: w = 3.98, d = 83, W = 8.0
DP Table:
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0 83 83 83 83 83 83]]

sol.x: [1]
Optimal value: 83
----------------------------------------
Row 6: w = 3.98, d = 88, W = 8.5
DP Table:
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0 88 88 88 88 88 88]]

sol.x: [1]
Optimal value: 88
---------------------------

#w=3.98
Fullfilled=772/852

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (0.765, 361, 6.0),
    (0.765, 392, 6.5),
    (0.765, 422, 7.0),
    (0.765, 452, 7.5),
    (0.765, 482, 8.0),
    (0.765, 512, 8.5),
    (0.765, 542, 9.0),
    (0.765, 572, 9.5),
    (0.765, 602, 10.0),
    (0.765, 633, 10.5)
]

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 0.765, d = 361, W = 6.0
DP Table:
[[  0   0   0   0   0   0   0]
 [  0 361 361 361 361 361 361]]

sol.x: [1]
Optimal value: 361
----------------------------------------
Row 2: w = 0.765, d = 392, W = 6.5
DP Table:
[[  0   0   0   0   0   0   0]
 [  0 392 392 392 392 392 392]]

sol.x: [1]
Optimal value: 392
----------------------------------------
Row 3: w = 0.765, d = 422, W = 7.0
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0 422 422 422 422 422 422 422]]

sol.x: [1]
Optimal value: 422
----------------------------------------
Row 4: w = 0.765, d = 452, W = 7.5
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0 452 452 452 452 452 452 452]]

sol.x: [1]
Optimal value: 452
----------------------------------------
Row 5: w = 0.765, d = 482, W = 8.0
DP Table:
[[  0   0   0   0   0   0   0   0   0]
 [  0 482 482 482 482 482 482 482 482]]

sol.x: [1]
Optimal value: 482
----------------------------------------
Row 6: w = 0.765, d = 512, W = 8.5
DP Table:
[[  0   0   0   0   0  

#w=0.765
Fullfilled=4970/4970

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (1.13, 289, 6.0),
    (1.13, 313, 6.5),
    (1.13, 337, 7.0),
    (1.13, 361, 7.5),
    (1.13, 386, 8.0),
    (1.13, 410, 8.5),
    (1.13, 434, 9.0),
    (1.13, 458, 9.5),
    (1.13, 482, 10.0),
    (1.13, 506, 10.5)
]

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 1.13, d = 289, W = 6.0
DP Table:
[[  0   0   0   0   0   0   0]
 [  0 289 289 289 289 289 289]]

sol.x: [1]
Optimal value: 289
----------------------------------------
Row 2: w = 1.13, d = 313, W = 6.5
DP Table:
[[  0   0   0   0   0   0   0]
 [  0 313 313 313 313 313 313]]

sol.x: [1]
Optimal value: 313
----------------------------------------
Row 3: w = 1.13, d = 337, W = 7.0
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0 337 337 337 337 337 337 337]]

sol.x: [1]
Optimal value: 337
----------------------------------------
Row 4: w = 1.13, d = 361, W = 7.5
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0 361 361 361 361 361 361 361]]

sol.x: [1]
Optimal value: 361
----------------------------------------
Row 5: w = 1.13, d = 386, W = 8.0
DP Table:
[[  0   0   0   0   0   0   0   0   0]
 [  0 386 386 386 386 386 386 386 386]]

sol.x: [1]
Optimal value: 386
----------------------------------------
Row 6: w = 1.13, d = 410, W = 8.5
DP Table:
[[  0   0   0   0   0   0   0

#w=1.13
Fullfilled=3976/3976

In [ ]:
import numpy as np

# Given data for w, d, and W
data = [
    (6.18, 183, 6.0),
    (6.18, 199, 6.5),
    (6.18, 214, 7.0),
    (6.18, 229, 7.5),
    (6.18, 244, 8.0),
    (6.18, 260, 8.5),
    (6.18, 275, 9.0),
    (6.18, 290, 9.5),
    (6.18, 305, 10.0),
    (6.18, 321, 10.5)
]


def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected

# Iterate through each set of w, d, W and solve knapsack problem using DP
for index, (w, d, W) in enumerate(data):
    print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")

    # Convert w and d to lists for compatibility with knapsack_dp function
    w_list = [w]
    d_list = [d]

    dp_table = knapsack_dp(W, w_list, d_list)
    optimal_value = dp_table[len(w_list)][int(W)]
    selected_items = find_selected_items(dp_table, w_list, W)

    print("DP Table:")
    print(dp_table)
    print()

    sol_x = np.zeros(len(w_list), dtype=int)
    for item in selected_items:
        sol_x[item] += 1

    print("sol.x:", sol_x)
    print("Optimal value:", optimal_value)
    print("-" * 40)


Row 1: w = 6.18, d = 183, W = 6.0
DP Table:
[[  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 183]]

sol.x: [1]
Optimal value: 183
----------------------------------------
Row 2: w = 6.18, d = 199, W = 6.5
DP Table:
[[  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 199]]

sol.x: [1]
Optimal value: 199
----------------------------------------
Row 3: w = 6.18, d = 214, W = 7.0
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 214 214]]

sol.x: [1]
Optimal value: 214
----------------------------------------
Row 4: w = 6.18, d = 229, W = 7.5
DP Table:
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 229 229]]

sol.x: [1]
Optimal value: 229
----------------------------------------
Row 5: w = 6.18, d = 244, W = 8.0
DP Table:
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 244 244 244]]

sol.x: [1]
Optimal value: 244
----------------------------------------
Row 6: w = 6.18, d = 260, W = 8.5
DP Table:
[[  0   0   0   0   0   0   0

#w=6.18
Fullfilled=2520/2520

#Conclusion-

Greedy Method=99.8% effective

Genetic Approach=86.5% effective

Knapsack(Dynamic approach)=99.7% effective

Knapsack(LPP Approach)-90% effective

Results

Function Code snippets-

  Distribution of Demands by Greedy Approach

In [ ]:
def distribute_demand(d, W):
    total_W = sum(W)
    distribution = [(W_i / total_W) * d for W_i in W]
    rounded_distribution = [int(round(dist)) for dist in distribution]
    adjustment = d - sum(rounded_distribution)

    if adjustment != 0:
        fractional_parts = [(distribution[i] % 1, i) for i in range(len(W))]
        fractional_parts.sort(reverse=True, key=lambda x: x[0])

        for _, idx in fractional_parts[:abs(adjustment)]:
            rounded_distribution[idx] += 1 if adjustment > 0 else -1

    return rounded_distribution

def get_formatted_results(data):
    formatted_results = []

    for i, w in enumerate(data['w']):
        d_value = data['d'][i]
        distribution = distribute_demand(d_value, data['W'])

        for j, W in enumerate(data['W']):
            if distribution[j] > 0:
                formatted_results.append(f"{w}\t{distribution[j]}\t{W}")

    return formatted_results

results = get_formatted_results(data)

for result in results:
    print(result)


Greedy Approach

In [ ]:
import numpy as np
def greedy_knapsack(W, w, d):
    w = np.array(w)
    d = np.array(d)

    n = len(w)
    total_weight = 0
    total_value = 0
    x = np.zeros(n)
    for i in range(n):
        if total_weight + w[i] <= W:
            x[i] = 1
            total_weight += w[i]
            total_value += d[i]
        else:
            fraction = (W - total_weight) / w[i]
            x[i] = fraction
            total_weight += w[i] * fraction
            total_value += d[i] * fraction
            break

    return x, total_weight, total_value

def generate_greedy_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)
    x, total_weight, total_value = greedy_knapsack(W, w, d)
    print("Weight vector (w):", w)
    print("Demand vector (d):", d)
    print("Selected fractions (x):", x)
    print("Total weight in knapsack:", total_weight)
    print("Total value in knapsack:", total_value)
    print()


Individual matrix and sol.x calculation iteratively row by row by knapsack approach(LPP )

In [ ]:
import numpy as np
from scipy.optimize import linprog

def generate_optimal_pattern(W, w, d):
    w = np.array(w)
    d = np.array(d)

    A = np.eye(len(w)) * (W // w)
    c = np.ones(len(w))
    A_ub = np.atleast_2d(w)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')

    print("A matrix:")
    print(A)
    print("sol.x:")
    print(sol.x)

def solve_knapsack_problems(data):
    for index, (w, d, W) in enumerate(data):
        print(f"Row {index + 1}: w = {w}, d = {d}, W = {W}")
        generate_optimal_pattern(W, [w], [d])
        print("-" * 40)

# Example call to solve_knapsack_problems with data
# data = [(w1, d1, W1), (w2, d2, W2), ...]
# solve_knapsack_problems(data)


Iteratively calculation on every width

In [ ]:
import numpy as np
from scipy.optimize import linprog
import pandas as pd

def solve_knapsack_problem(df, total_width):
    df['w'] = pd.to_numeric(df['w'], errors='coerce')
    w = df.w.values.astype(float)
    df['d'] = pd.to_numeric(df['d'], errors='coerce')
    d = df.d.values.astype(float)

    A = np.eye(df.shape[0]) * (total_width // w)
    c = np.ones_like(w)
    A_ub = np.atleast_2d(w)
    b_ub = np.atleast_1d(total_width)

    sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')
    sol_dual = linprog(-d, A_ub=A.T, b_ub=c, bounds=(0, None), method='highs')

    duals = -sol_dual.ineqlin.marginals

    def solve_knapsack(W, w, duals):
        return linprog(-duals, A_ub=np.atleast_2d(w), b_ub=np.atleast_1d(W), bounds=(0, np.inf), method='highs')

    for _ in range(1000):
        duals = -sol_dual.ineqlin.marginals
        price_sol = solve_knapsack(total_width, w, duals)
        y = price_sol.x

        if 1 + price_sol.fun < -1e-4:
            A = np.hstack((A, y.reshape((-1, 1))))
            c = np.append(c, 1)
            sol = linprog(c, A_ub=-A, b_ub=-d, bounds=(0, None), method='highs')
        else:
            break

    result = (np.ceil(sol.x).astype(int), A.T)
    return result

# Example usage:
# data = {
#     'w': [1.4, 0.7, 3.41, 3.98, 0.765, 1.13, 6.18],
#     'd': [9, 4, 21, 22, 4, 6, 7]
# }
# df = pd.DataFrame(data)
# total_width = 6.0
# solve_knapsack_problem(df, total_width)


Genetic approach to calculate demand distribution

In [ ]:
import numpy as np

# Genetic Algorithm Parameters
POPULATION_SIZE = 100
NUM_GENERATIONS = 200
MUTATION_RATE = 0.05

def fitness(solution, d, W):
    total_demand = np.sum(solution)
    if total_demand != d:
        return -np.inf
    total_weight = np.sum(np.array(solution) * np.array(W))
    return -total_weight

# Initialize population
def initialize_population(population_size, num_weights):
    population = []
    for _ in range(population_size):
        chromosome = np.random.randint(0, 10, size=num_weights)
        population.append(chromosome)
    return np.array(population)

# Selection: Tournament selection
def tournament_selection(population, fitness_values, tournament_size=3):
    idx = np.random.choice(len(population), tournament_size, replace=False)
    tournament_fitness = fitness_values[idx]
    return population[idx[np.argmax(tournament_fitness)]]

# Crossover: Single point crossover
def crossover(parent1, parent2):
    crossover_point = np.random.randint(len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return child1, child2

# Mutation: Bit flip mutation
def mutate(solution, mutation_rate, max_value):
    mutated_solution = solution.copy()
    for i in range(len(mutated_solution)):
        if np.random.rand() < mutation_rate:
            mutated_solution[i] = np.random.randint(0, max_value + 1)
    return mutated_solution

# Genetic Algorithm
def genetic_algorithm(d, W):
    population = initialize_population(POPULATION_SIZE, len(W))
    max_value = int(np.ceil(d / min(W)))

    for generation in range(NUM_GENERATIONS):
        fitness_values = np.array([fitness(individual, d, W) for individual in population])
        new_population = []
        for _ in range(POPULATION_SIZE // 2):
            parents = [tournament_selection(population, fitness_values) for _ in range(2)]
            offspring1, offspring2 = crossover(parents[0], parents[1])
            offspring1 = mutate(offspring1, MUTATION_RATE, max_value)
            offspring2 = mutate(offspring2, MUTATION_RATE, max_value)
            new_population.extend([offspring1, offspring2])
        population = np.array(new_population)

    fitness_values = np.array([fitness(individual, d, W) for individual in population])
    best_solution_idx = np.argmax(fitness_values)
    best_solution = population[best_solution_idx]
    total_weight = np.sum(np.array(best_solution) * np.array(W))

    return best_solution, total_weight

def solve_demand_distribution(data):
    formatted_results = []
    for i in range(len(data['w'])):
        w = data['w'][i]
        d_value = data['d'][i]
        best_solution, total_weight = genetic_algorithm(d_value, data['W'])

        for j, W_value in enumerate(data['W']):
            if best_solution[j] > 0:
                formatted_results.append(f"{w}\t{best_solution[j]}\t{W_value}")

    return formatted_results


Knapsack(Dynamic programming)

In [ ]:
import numpy as np

def knapsack_dp(W, w, d):
    n = len(w)
    dp = np.zeros((n + 1, int(W) + 1), dtype=int)

    for i in range(1, n + 1):
        for j in range(1, int(W) + 1):
            if int(w[i - 1]) <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - int(w[i - 1])] + d[i - 1])
            else:
                dp[i][j] = dp[i - 1][j]

    return dp

def find_selected_items(dp, w, W):
    selected = []
    i = len(w)
    j = int(W)

    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected.append(i - 1)
            j -= int(w[i - 1])
        i -= 1

    return selected